apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-timeline-test
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: canary-rollout-ingress
    repoURL: https://github.com/testcodefresh/rollouts-demo.git
    targetRevision: blue
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
  ignoreDifferences:
    - kind: Service
      jsonPointers:
        - /spec/selector/rollouts-pod-template-hash
