apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-tag
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: canary-rollout-ingress
    repoURL: https://github.com/testcodefresh/rollouts-demo.git
    targetRevision: test-branch
  destination:
    name: in-cluster
    namespace: test-date
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
